### ISSUE TITLE
Implement graph visualization of product relations

### ISSUE THREAD

**Issue by TaiSakuma** [simonsobs/acondbw#23]
- Implement graph visualization of product relations
    - The products in the DB are related to one another and can be represented as a graph; products as vertices and relations as edges. The products and their relations can be visualized as a (interactive) graph by a number of [graph visualization tools](https://www.google.com/search?q=%22graph+visualization+tools%22) available.

**Comment by msyriac** [comment]
Weird coincidence -- I just implemented this with GraphViz for analysis working group products yesterday. Here it is: https://github.com/simonsobs/ssia_tools
